### ISSUE TITLE
Not passing `singleFilterDescription` to `saveFileDialog` can freeze

### ISSUE THREAD

**Issue by beef331** [Patitotective/tinyfiledialogs.nim#1]
The code `aSingleFilterDescription = cstring singleFilterDescription` which means it sends a `cstring` which can point to `\0` which seems to be capable of causing code to lock up.

**Comment by Patitotective** [comment]
Hi, thanks for reporting this, however I can't seem to get this to freeze in my machine.
It may have to do with the file dialog backend (mine is using python-dbus probably).
I'm not very knowledgeable about this, a solution I can think of right now would be to pass `nil` when `singleFilterDescription` is empty. Do you think this would work? 😆
Thanks.

**Comment by beef331** [comment]
Yes that would likely suffice

**Comment by Patitotective** [comment]
I think it is fixed now in the new version v1.1.2
Thanks

**Comment by beef331** [comment]
Well sorry for wasting your time, that did not resolve it 😄 

On my system it's reproducible with the following, I'll investigate it later
```nim
import tinydialogs

var dest =
  when defined(bug1):
    saveFileDialog("Save Level", "", ["*.zip"]) # No window presented
  elif defined(bug2):
    saveFileDialog("Save Level", "", ["*.zip"], "\0") # No window presented
  else:
    saveFileDialog("Save Level", "", ["*.zip"], "a")



echo dest

```
